### ISSUE TITLE
Breaks drop down menus on some websites

### ISSUE THREAD

**Issue by djlongy** [ansh/jiffyreader.com#108]
Tested on shavershop.com.au checkout screen
A few other shopping websites the plug-in breaks menus and filters also.

**Comment by asieduernest12** [comment]
@djlongy would you be able to provide screenshots or video recording which would help with triage.
but i recommend getting the latestt release [here](https://github.com/ansh/jiffyreader.com/releases/tag/0.0.3) and testing before
