### ISSUE TITLE
[BUG] Breaks DuckDuckGo Top-Bar

### ISSUE THREAD

**Issue by ShaikaJar** [ansh/jiffyreader.com#110]
When i open DuckDuckGo and search for something I SOMETIMES can't click on the Top-Bar to switch to Images or the Map.
It occurs even when i  the reading mode isn't on somehow.
I only noticed it, when the i had the extension installed.  Removing the extension removed the problem

**Comment by Explosion-Scratch** [comment]
The extension seems to remove event listeners from all elements that it edits. This means that complicated sites will randomly have bugs, as you can see from the screen recording upon clicking turning on bionic reading (via bookmarklet) it causes this bug:

https://user-images.githubusercontent.com/61319150/171517443-f4977ce8-b9bf-4bd8-a0be-0c4c5ef8100c.mp4

**Comment by asieduernest12** [comment]
the specific issue of removing event listeners was fixed in 0.0.3 kindly try please
unfortunately we still have some bugs with duckduckgo which may be present on some dynamic side and really edge case 
where text duplicates itself. Hopefully someone has a solution to it.

**Comment by asieduernest12** [comment]
> The extension seems to remove event listeners from all elements that it edits. This means that complicated sites will randomly have bugs, as you can see from the screen recording upon clicking turning on bionic reading (via bookmarklet) it causes this bug:
> 
>  It.removes.the.event.listener.mp4

did not realize you were using bookmarklet, if the bookmarklet is based on any implementation pre 0.0.3 then that explains why the listener is removed.

**Comment by asieduernest12** [comment]
fixed by #85 kindly 
@ShaikaJar kindly test with release 0.0.6
