### ISSUE TITLE
[BUG] Extension can't be toggled off

### ISSUE THREAD

**Issue by mahdithedev** [ansh/jiffyreader.com#120]
**Describe the bug**
The  extension can't be toggled off sometimes and a full page refresh is required

**To Reproduce**
1. Go to https://draftjs.org/docs/advanced-topics-entities/
2. Toggle the extension on
3. now try to toggle it off you can't

** Browser information**
- Browser: Google Chrome Version 102.0.5005.63 (Official Build) (64-bit)

**Comment by asieduernest12** [comment]
@mahdithedev sorry for the inconvenience

I was unable to reproduce the issue with any of these versions release 1.0.0 on the chrome store and [release 0.0.7](https://github.com/ansh/bionic-reading/releases/latest/download/chrome.zip)

kindly confirm you are on the latest release of the extension on the chrome store or using the latest 0.0.7-alpha release of the extension if you are not already using any of these versions.
