### ISSUE TITLE
delayed upload of new release to various stores (chrome,firefox, etc)

### ISSUE THREAD

**Issue by asieduernest12** [ansh/jiffyreader.com#121]
@ansh @X140Yu 
so the versions on chrome store and firefox store seem outdate and the last time they were updated for chrome was may 30

can we have a action or regular weekly store release setup so that the stores can have the news codes with features and fixes 

im still learning about github actions so its slow for me.

**Comment by mahdithedev** [comment]
I uninstalled the extension and installed it again via the chrome store the problem is fixed thanks

**Comment by asieduernest12** [comment]
> @ansh it looks like safari ext can be generated the same way we generate per browser builds. [#48 (comment)](https://github.com/ansh/jiffyreader.com/issues/48#issuecomment-1139260816)

@jhonalino im closing this, can you open a new issue for the safari feature if you are working on it please.
