### ISSUE TITLE
[BUG] It messes with writting a new tweet

### ISSUE THREAD

**Issue by vgaltes** [ansh/jiffyreader.com#138]
When writing a new tweet it changes the direction of writing and it seems that disables the backspace (only delete works)
<img width="458" alt="bug" src="https://user-images.githubusercontent.com/862679/175821378-6fe15697-66ca-4ab2-afc4-9bc15b5fe32f.png">
.

**Comment by asieduernest12** [comment]
interesting this issue is mostly occuring on twitter as they are using a custom approach of achieving the input form for new tweets

**Comment by asieduernest12** [comment]
version 1.0.8 will be publish to the chrome store to resolve this. You can however download it presently from the releases page
[https://github.com/ansh/jiffyreader.com/releases/tag/1.0.8](here)
