### ISSUE TITLE
Google Books Chrome Extension

### ISSUE THREAD

**Issue by Happy1979** [ansh/jiffyreader.com#147]
The very first version of Jiffyreader which was label Bionic Reading 0.0.1 the Inspect views shows up as service worker. 
This version works with Google Books per page in a weird way, so hoping you can get this to work better. 
So here is how I get this to work on chrome browser or chromium 
I am using developer mode is enable and Load unpacked file. 
Then open any of my google books through webapp play,google.com
Next pin app so I can access app extension easier 
Next select Toggle Reading Mode 
After that Bionic Reading works fine, then I can not get the next page to load. 
To get the next page to load, I have turn off the Toggle Reading mode and refresh the webpage, then I can load the next page. 
I have to repeat this for each page to get Bionic Reading to work. 
I have try all the other version and no other them work like this one.
I can supply whatever you need to help with this

**Comment by asieduernest12** [comment]
Thanks for reporting. Will look into it.

**Comment by asieduernest12** [comment]
@Happy1979 [here](https://github.com/ansh/jiffyreader.com/releases/tag/0.0.1.1-google-books) is the release that works with google books. It is quite old so not actively maintained or maintained.

You can download the zip then open the extensions page in chrome and use the load unpack to navigate to the extracted copy of the zip and choosing the manifest file.

**Comment by asieduernest12** [comment]
@Happy1979 the latest release 1.0.8.12 supports Google Books too.

Enjoy all the features and new fixes with the latest release.

**Comment by Happy1979** [comment]
I can confirmed this has been fixed and working 
Thank you very much
