### ISSUE TITLE
[BUG] Firefox - Doesn't seem to work on local files.

### ISSUE THREAD

**Issue by ryloric** [ansh/jiffyreader.com#148]
Doesn't change text on a local html file opened in firefox. There's no special permission needed to operate on local files unlike chrome, so permissions are not a problem as far as I can tell. I tried using a couple of other addons from AMO which do the same job and they worked fine, although I'd like to use this because of the easy customization available.

Desktop (please complete the following information):
 - OS: Linux 
 - Browser: Firefox Developer Edition 103.0b5
 - Version: Latest

Thanks!

**Comment by asieduernest12** [comment]
Thanks for reporting. We will look into it.

**Comment by asieduernest12** [comment]
@ryloric Install the bookmarklets which work with local files. 
Follow the steps [here](https://github.com/ansh/jiffyreader.com#bookmarklet)

**Comment by asieduernest12** [comment]
Local files support is fixed in the latest release 1.0.8.12 available on Chrome store and Firefox store
