### ISSUE TITLE
[FEATURE] Open the bionic mode by click a button

### ISSUE THREAD

**Issue by denglizong** [ansh/jiffyreader.com#150]
Thanks for such an amazing tool! I think that it is neccessary to add a function of openning the bionic mode by click a button. Because I shut the bionic mode in most case, and only open it in some specical case. Global on and off is troublesome to some extent. Thanks again.

**Comment by asieduernest12** [comment]
@denglizong there is a shortcut feature just for this that you can customize to whatever key combinations you want.
Follow the tips [here](https://github.com/ansh/jiffyreader.com#shortcut)

**Comment by asieduernest12** [comment]
Install the jiffy bookmarklets. find the steps here https://github.com/ansh/jiffyreader.com#bookmarklet
