### ISSUE TITLE
Right to left support

### ISSUE THREAD

**Issue by Daklyy** [ansh/jiffyreader.com#155]
Is there a way i can flip the settings so that the saccades (the bold part) would be the end part of the word instead of the first part of it, because i want to apply jiffy reader to (arabic, kurdish) and these are right to left languages, but jiffy reader makes the left part of the words bold which makes sense for english and other left to right languages but not for right to left languages. Some extensions already allow this by replacing the settings of the two parts of the word so that the right part becomes bold instead of the lefts part.

**Comment by asieduernest12** [comment]
@Daklyy this extension should naturally be compatible with content online that is right to left rendered.

file:///home/linuxdev/Pictures/Screenshot%20from%202022-07-28%2003-41-57.png

**Comment by Daklyy** [comment]
Yes i was aware of this, but there are situations where it doesn't work and you might want to change the settings so that the part that is being bold would be the second part of the word not the first, so that we can get over the problem when the default fails to recognize where the text starts. The extension is great i love it but i though a little more control with the settings would be nice.
![EA25BB3B-70A8-4E11-99AC-31A406391469](https://user-images.githubusercontent.com/102173936/181479383-e52ac271-fb77-4f4e-8783-9983dbc9adc3.png)

**Comment by Daklyy** [comment]
I think the problem was not with the extension but with the web page i was trying to apply the extension to, turns out the webpage is broken in every possible ways. Also i went in and edited the code so that is does what i talked about previously and it did work but even then it worked perfectly on every page except that one webpage. Thank you for your demonstration
