### ISSUE TITLE
[BUG] Missing Words Google Play Books 

### ISSUE THREAD

**Issue by Happy1979** [ansh/jiffyreader.com#159]
The issue is when you are using the Google Play books website when you enable reading mode you can not see all the text it gets push out. 
This was tested on the Chrome webstore version and the load the developer version. 
1.0.8.12 and 1.0.8.1300 
The OS tested 
Debian 10 
Windows 10 
Google ChromeOS 103.

Also tested using the zoom - and + option to see if that makes a difference. It does help show more of the missing words. 
Fixations setting is my guess where this is happening. 

Once again AWESOME APP and THANK YOU VERY MUCH

**Comment by asieduernest12** [comment]
@Happy1979 please share two screenshots if possible. One without the problem and one with the problem.

We also excited that your are enjoying the app. Please leave a rating or review on either chrome or firefox store. 
It goes a long way help us and show others that this is the greatest extension that facilitates bionic reading.

**Comment by Happy1979** [comment]
Here are two screenshots as requested. 
Sorry about the close and reopened on this ticket 
![ScreenshotNoJiffyreader](https://user-images.githubusercontent.com/108884990/181766121-7fb831fa-15b5-4ae6-aea2-87d17697f9ea.png)
![ScreenshotwithJiffyreader](https://user-images.githubusercontent.com/108884990/181766127-20c79b49-f8ec-455d-8443-613e3b2c0e68.png)

I have done a review 5 stars and sharing this app with anyone I can think of for sure.

**Comment by asieduernest12** [comment]
@Happy1979 we can implement a styling override for google books to make the page scrollable which should allow you scroll around.

**Comment by Happy1979** [comment]
okay, let me know when the new version is ready to test be happy to do that

**Comment by asieduernest12** [comment]
@Happy1979 1.0.9.1001-development is available in the releases with a fix for this issue, but you may wait a few hours to a day for 1.0.9.1001 to be available on the store with an automatic update.

**Comment by Happy1979** [comment]
awesome news, will report my finding after this weekend of testing thank you again for a quick turn on this issue.

**Comment by Happy1979** [comment]
Very very very sorry for not doing a review earlier on this. 
Everything is working as you said it was 
THANK YOU Very much,
