### ISSUE TITLE
[BUG] doesn't work for canvas reading assignments

### ISSUE THREAD

**Issue by Bujao080** [ansh/jiffyreader.com#160]
**Describe the bug**

**To Reproduce**
1. Go to 'https://app.perusall.com/courses/ctn102-comptia-net-202301-202301-july-25-2/read-comptia-net-n10-008-lesson-06-supporting-ipv4-and-ipv6-networks-24-pages?assignmentId=LzyALE6jJDouTKJ5B&part=1'
2. doesn't work for the reader in the middle of the page

![reader issue](https://user-images.githubusercontent.com/110194779/181611763-dbc7e43d-0191-46c0-bf32-93ae9d388560.JPG)

**Desktop (please complete the following information):**
 - OS: window 10
 - Browser: chrome

Works of the outside of the page but not the center

**Comment by asieduernest12** [comment]
@Bujao080 was this working for you before?
is the canvas area editable (are you able to edit text in the canvas area)?

**Comment by asieduernest12** [comment]
@Bujao080 the link you shared is not accessible and preventing me from validating the issue. 
However i suspect the area is an editable field which is ignored by the jiffy parser to prevent issues first reported in #139 and #157
