### ISSUE TITLE
[BUG] Chrome report as not trusted by by enhanced safe browsing

### ISSUE THREAD

**Issue by dcpc007** [ansh/jiffyreader.com#161]
**Describe the bug**
When clik on install the extension on chrome, a popup warns about "not safe" ?

**Screenshots**
![image](https://user-images.githubusercontent.com/847516/181720227-63e34a30-5322-43b0-a931-8d15aee57140.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version 103.0.5060.134 (Official Build) (64-bit)

**Comment by asieduernest12** [comment]
The chrome store team will classify an extension as trusted after a period of six months ideally where the extension has not breached in any serious way the policies or guide lines for chrome extensions. 

Basically its subjectively all the decision of the chrome team weather we are trust worthy to them or not.
