### ISSUE TITLE
[BUG] Bionic Reading "about" link is wrong in readme

### ISSUE THREAD

**Issue by maxxyme** [ansh/jiffyreader.com#164]
**Describe the bug**
The link to a so-called "about" page: https://jiffyreader.com.com/about/ in the "What is Bionic Reading?" section: https://github.com/ansh/jiffyreader.com#what-is-bionic-reading is wrong.

This domain is listed in uBlock's badware list: https://github.com/uBlockOrigin/uAssets/blob/master/filters/badware.txt#L39

**To Reproduce**
Read description above.

**Expected behavior**
An actual "about" page on jiffyreader.com is displayed, which I doubt can happen (for now?) because https://jiffyreader.com/about is in fact 404...

**Comment by asieduernest12** [comment]
Did not realise we incorrectly changed the reference a while back. It should be fixed now and should actually redirect to https://bionic-reading.com/about

**Comment by asieduernest12** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/filters/badware.txt#L39

**Comment by maxxyme** [comment]
@asieduernest12 not your domain but com.com as in " https://jiffyreader.com.com/about/"
I think you initially meant "https://jiffyreader.com/about/" but ended up with 2x ".com"
