### ISSUE TITLE
[BUG] Extension does not work for notion.so

### ISSUE THREAD

**Issue by tyrcho** [ansh/jiffyreader.com#166]
**Describe the bug**
Extension does not work for notion.so

**To Reproduce**
1. Activate the extension
2. Open a page on notion.so, for instance this is a public page https://www.notion.so/Contrat-social-en-JDR-8a16e487a1754772b7b0dce8e8729b0c

**Expected behavior**
Proper "jiffy look" on all the page

**Screenshots**
<img width="756" alt="image" src="https://user-images.githubusercontent.com/700260/182414169-dd28d896-8bb2-4544-a5d2-f7377880af37.png">
Only the TOC is "jiffied"

**Desktop (please complete the following information):**
 - OS: macOS 12.5
 - Browser chrome
 - Version 103.0.5060.134 (Official Build) (x86_64)

**Additional context**
Other sites seem to be working fine

**Comment by asieduernest12** [comment]
It looks like we might not be supporting notion completely. JiffyReader conflicts with their code and I advice you to not use JiffyReader on Notion at least for now.

We will investigate and see if some remedy is possible.
My browser kept freezing up while checking notion.

**Comment by ansh** [comment]
@tyrcho Sites like Notion (where text is editable and especially notion where you can do so many things with text) are extremely difficult to get working with Jiffy.

**Comment by asieduernest12** [comment]
Last time we checked it seemed notion had implemented some algorithm to reset nodes when they are altered by foreign code (code not delivered by notion).

Their implementation is causing a death loop which ends up freezing the tab completely by spiking cpu usage and not really something we can fight with.
