### ISSUE TITLE
[BUG] Tabs without suitable url may not work properly for everything

### ISSUE THREAD

**Issue by bananaboy139** [ansh/jiffyreader.com#168]
**Describe the bug**
When I click on the icon, I always get: 
Tabs without a url may not work properly
Reload the tab with valid url and try again
[FAQ](https://github.com/ansh/jiffyreader.com#FAQ)
[Report Issue](https://github.com/ansh/jiffyreader.com#reporting-issues-bugs-and-feature-request)
[About Us](https://www.jiffyreader.com/)

**To Reproduce**
So far I've tried on:
reddit
gmail
github

**Desktop:**
 - OS: Windows 10
 - Browser: firefox
 - Addon Version: 1.0.9.1001

**Comment by BenGost** [comment]
Hello,
Same problem on Firefox (it worked before the update)
Have a good day

**Comment by asieduernest12** [comment]
@bananaboy139 thank you for the report, firefox is really not insterested in smiling on the new updates while other chromium browsers just sip wine with the new updates
 but we will give it some more eyes over the weekend and see what magic we can pull off.

cheers

**Comment by asieduernest12** [comment]
@bananaboy139 @BenGost fortunately firefox allows you to download any of the prior versions, those should still work fine if you are able to grab them.

**Comment by ansh** [comment]
I believe this issue only happens when opening a pre-existing tab. If you refresh the page, it should fix it. @bananaboy139

**Comment by faurehu** [comment]
I just wanted to report the same issue.

**Comment by ran-dall** [comment]
Same issue. Refreshing the page doesn't fix it.

**Comment by asieduernest12** [comment]
resolved the issue with latest release 1.0.9.1002
Cheers

**Comment by ran-dall** [comment]
This issue still occurs.

**Comment by asieduernest12** [comment]
@ran-dall can you share some details such as the website or full URL if the site content is public or a public page of the site where the issue is occurring.

**Comment by ran-dall** [comment]
@asieduernest12 It's still happening for all sites for me.

**Comment by asieduernest12** [comment]
@ran-dall downgraded? what do you mean by that?
did you mean you installed an older version?

I am not able to reproduce the issue after updating to 1.0.9.1002 but some sites may still show the tab error if you click on the jiffy icon immediately you reload the tab without waiting for a bit. Ideally wait till the icon shows the on/off indicator, which should occur within the first second of reload unless the page you are opening is loading a whole MV-EVERGIVEN of assets

It would also help to restart your browser if you have not done so already.
Sharing a video recording of what is happening would also be helpful, at least showing two websites that you are encountering the issue with and also provide specific example sites that are publicly accessible without signing up.

**Comment by ran-dall** [comment]
@asieduernest12 Yeah, so when the latest version wasn't working, I re-downloaded the previous version, and it must have thrown something off. I deleted the extension and reinstalled your latest-latest release, and now it seems to be working. My bad. Thank you for the support.

**Comment by asieduernest12** [comment]
![ThankYouGraciasGIF (2)](https://user-images.githubusercontent.com/20851930/183327785-27c7cbfd-a619-4e2f-941c-093e0b243e42.gif)
