### ISSUE TITLE
[BUG] Opens Github again and again

### ISSUE THREAD

**Issue by reaseno** [ansh/jiffyreader.com#172]
**Describe the bug**
From time to time the Github page https://github.com/ansh/jiffyreader.com#first-installation-welcome opens in a new tab. I can't see any reason for this. Does it do this for release notes, or is there a hotkey?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi and Firefox

**Comment by asieduernest12** [comment]
@reaseno i am unable to reproduce this behaviour for vivaldi, firefox , brave and chrome

By the implementation the first-installation-welcome link will be opened the very first time you install the extension and a record is saved which is checked every other time an installation or update happens.
If some other process or extension is deleting the record then the extension will open the first-installation-welcome page again.
But that operation only executes when an installation happens so unless your browser is reinstalling the extension all by itself.

Or alternatively you could have been on older versions and the browser must have been updating them in the order according to their version number, all proir versions would trigger opening the repo homepage but in those versions they would jump to the faq section.
