### ISSUE TITLE
[BUG] gradient fonts disappear

### ISSUE THREAD

**Issue by raphaelp-github** [ansh/jiffyreader.com#183]
**Describe the bug**
Not efficient on fonts that are blue (natively)

**Reproduce on a website**
1. Visit this link: 'https://www.frandroid.com/android/applications/1430595_telegram-veut-revolutionner-sa-messagerie-mais-apple-len-empecherait' 
- [x] check or mark with an x to indicate that the link is publicly accessible and also requires no account to be created.

**Expected behavior**
Text visibility.

**Screenshots**
![image](https://user-images.githubusercontent.com/34160362/184530911-6ac87039-7a15-47f9-80ab-86da310703a0.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Brave
 - Version: 1.42.88
 - Extension version: 1.0.9.1006

**Comment by asieduernest12** [comment]
@raphaelp-github adujst the opacity slider to 100%
some websites use color gradients on their text which will disappear from the page when opacity is less than 100%
