### ISSUE TITLE
[FEATURE] Automatically reduce the opacity slider to 100%

### ISSUE THREAD

**Issue by raphaelp-github** [ansh/jiffyreader.com#184]
**Is your feature request related to a problem? Please describe.**
https://github.com/ansh/jiffyreader.com/issues/145

**Describe the solution you'd like**
Automatically reduce the opacity slider to 100% when websites use color gradients on their text, which disappear from the page when the opacity is below 100%.

**Comment by asieduernest12** [comment]
@raphaelp-github sorry websites don't tell you they are using color gradients and you have to dig through their css or make a guess that they are.

There is no standard way to implement gradients that means there is no optimum way to detect it and as such will be a headache.

Lets leave this open and see if we can a kind person to suggest a good approach or even take care of implementing a basic logic that tells us if gradients are beign used on text. 

Alternatively we will add a prompt that on the slider that will alert you of gradient text potentially becoming invisible.

**Comment by raphaelp-github** [comment]
@asieduernest12 Is there no recurrence indicating the color gradients used in the CSS file?

**Comment by asieduernest12** [comment]
@raphaelp-github as of now i dont know a good way off the top of my head to solve this, and its going to involve digging around through documenation online. Frankly if the slider works on 100% then there is no real benefit to investigate this further when the issue is not widely impacting usage.

**Comment by asieduernest12** [comment]
@raphaelp-github equally you can set the opacity 100% and the extension will remember it for next time, all configurations are remembered automatically so you can set it how you prefere and forget about it

**Comment by raphaelp-github** [comment]
The comfort of use (...). I will not systematically make a setting every time a new site comes into conflict.

**Comment by asieduernest12** [comment]
@raphaelp-github for confort of use set the opacity slider for global to 100% and you can forget about it setting it every again.
