### ISSUE TITLE
[BUG] Doesn't work on addons.mozilla.org

### ISSUE THREAD

**Issue by ofaurax** [ansh/jiffyreader.com#188]
**Describe the bug**
Can't use the extension on a page like https://addons.mozilla.org/en-US/firefox/addon/jiffy-reader/

I DON'T say I'm unable to install it, but to use the extension (bold characters) on addons.mozilla.org pages

**To Reproduce**
Go to https://addons.mozilla.org/en-US/firefox/addon/jiffy-reader/
Try to activate the extension

**Reproduce on the extension**
1. Go to https://addons.mozilla.org/en-US/firefox/addon/jiffy-reader/
2. Try to activate the extension
3. I get "page non détectée" in french in the little popup window

**Desktop (please complete the following information):**
 - OS: Linux Mageia 8
 - Browser: Firefox
 - Version: 91.12.0esr 
 - Extension version : 1.0.9.1010

**Comment by asieduernest12** [comment]
@ofaurax that page is restricted by the firefox and cannot be supported through the extension. 
If you really want to use the extension on that page then follow the bookmarklet guide

However there will be an update that will show more constructive errors per browser

**Comment by ofaurax** [comment]
Ho, it makes perfectly sense: if an extension manipulates "addons.mozilla.org" content, it could lead to serious troubles!

**Comment by asieduernest12** [comment]
@ofaurax exactly
