### ISSUE TITLE
Update the website to include Firefox and Edge extensions

### ISSUE THREAD

**Issue by armaccloud** [ansh/jiffyreader.com#192]
The website https://www.jiffyreader.com/ only contains a mention and link to the Chrome extension.
This request is for updating the website, so the Firefox and Edge extensions are also mentioned.

**Comment by asieduernest12** [comment]
@armaccloud sure. Hope JiffyReader is serving you well.

**Comment by armaccloud** [comment]
> @armaccloud sure. Hope JiffyReader is serving you well.

It is! I like how it works well on most webpages.
Thank you for creating this software,

**Comment by asieduernest12** [comment]
@armaccloud thank you for opening this issue which is now resolved
