### ISSUE TITLE
[BUG] Settings are never saved (global or site)

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [ansh/jiffyreader.com#195]
**Describe the bug**
When I set the option On whether Globally or for the Site once the tab is closed it never keeps it on for the next time I visit the site, or any site.

**To Reproduce**
1. Activate JR
2. Close tab
3. Come back to same site and it's off

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser : Firefox 105.0.3 x64
 - Extension version : 1.0.9.1010

Also would be great to have the option to have it on by default everywhere :)

**Comment by asieduernest12** [comment]
@YetAnotherDevWannabe interesting, we have not particularly run into such a problem 

yout can use the turn on always button near the very bottom to activate turn on always always
![image](https://user-images.githubusercontent.com/20851930/195993761-e7f3e208-c189-44cf-94c9-d8d7d7d89ffb.png)

**Comment by asieduernest12** [comment]
you can use that `turn on always` button together with the preferences to customize when and where JR will auto activate.
Either for all sites if you use turn on always with global or just for a specific site if you use it with `site (for this site)`

**Comment by YetAnotherDevWannabe** [comment]
mine doesn't look like that at all.
![image](https://user-images.githubusercontent.com/6054349/196008582-44629036-c1cb-432d-a277-a321d365f5f3.png)
and there is no option in firefox addon management for JR.

**Comment by asieduernest12** [comment]
@YetAnotherDevWannabe you need to scroll down, there are more controls below the slider shown in your image

**Comment by YetAnotherDevWannabe** [comment]
Oh wow ok, maybe add a scrollbar :P  will try again

**Comment by asieduernest12** [comment]
@YetAnotherDevWannabe you are welcome, firefox adds a scrollbar automatically.

**Comment by asieduernest12** [comment]
Enjoy. Remember to support the project through a donation or spreading the word about JiffyReader.
