### ISSUE TITLE
[BUG] Not working google playbooks

### ISSUE THREAD

**Issue by paulcgar** [ansh/jiffyreader.com#196]
**Describe the bug**   "Chrome is up to date
Version 107.0.5304.88 (Official Build) (64-bit)"

Just downloaded and installed on windows 10 Thinkpad Tablet. Not working on google playbooks.
I see the rabbit - it is pinned, and when I open a book in playbooks and click on nothing happens.
I selected specific sites and only want to use it in playbooks. 
When in playbooks and I click the rabbit the pop up window will go Bionic when I turn it on but my open book will not.

**Additional context**

**Comment by asieduernest12** [comment]
Hi @paulcgar this situation may happen if the book reesource is not an epub, only epub books in google playbooks are compatible with JiffyReader.

Alternatively you can convert the pdf version of the book if you have access to it by [following these steps](https://github.com/ansh/jiffyreader.com#pfd-support-convert-pdf-files-to-epub-or-html)
