### ISSUE TITLE
[BUG] Jiffy is "ON" even when "not activated"

### ISSUE THREAD

**Issue by morganekath** [ansh/jiffyreader.com#197]
**Describe the bug**
When adding the extension, any website is on bionic reading mode (as you can see on the screenshot N°1). The thing is, i can't disable it to have a "normal" format. And when clicking on "activate", precisely to do that, the bionic effect is juste "more visible", the bold letters are bolder and the light letters are lighter (see screenshot N°2). 
So, my problem is that i need to have the possibility to disable the bionic mode (specially because i need to present to others and show them stuff). And the second thing is that the "automatic mode" shown in the screenshot N°1 is what i want to have, but when activating the extension it's too bold/light to be readable for me.

**To Reproduce**
Steps to reproduce the behavior on extension or a specific website:

**Reproduce :
1. After dowloading the extension 
2. Go to any website and recharge the page
3. see that the feature is already on without activation of the feature
4. Click on the extension and see that when activating the feature, you'll have bolder letters and lighter ones (with a good application of the options you have choosen)

**Expected behavior**
When downloading the extension, i expected it to have an option to disable the bionic reading function. So i dont know if it's a bug or juste a feature that is not accessible yet. 

**Screenshots**
N°1 : 
![image](https://user-images.githubusercontent.com/119038952/204087206-ac1a48ed-5a39-4472-9dd9-3a2b225be73c.png)

N°2 : 
![image](https://user-images.githubusercontent.com/119038952/204087524-aef7725c-860a-4ab4-a3c6-d6942abe9c1e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 family
 - Browser : Opera
 - Version : 92.0.4561.43
 - Extension version : 1.0.9.1010

**Comment by morganekath** [comment]
> @morganekath Why did you close the issue? Was your problem resolved?

Yes ansh. I don't know what was the problem I just tried to uninstal the extension and install it again and it worked (though closing/re-opening the browser didn't before 😅)

Thank you!

**Comment by ansh** [comment]
Glad it was resolved! Please consider leaving a review on Chrome Extension Store or Firefox Addons Store if you enjoyed using Jiffy.

Thank you!
