### ISSUE TITLE
When editing in Chinese, The first key will be recognized as a letter

### ISSUE THREAD

**Issue by ethan-ih** [ansh/jiffyreader.com#198]
**Describe the bug**
When I edit in Chinese, the first key I type becomes a letter. This seems to be a problem for most web site editors, including, but not limited to, Telegram and discord.

**To Reproduce**
Steps to reproduce the behavior on extension or a specific website:

**Reproduce on the extension**

**Reproduce on a website**
1. Visit this link: '...' 
- [ ] check or mark with an x to indicate that the link is publicly accessible and also requires no account to be created.

**Expected behavior**
do not control the Input Box

**Screenshots**
<img width="599" alt="image" src="https://user-images.githubusercontent.com/105411793/204968102-3bf07b71-e834-42f8-b65c-7ff68dcacf20.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOs]
 - Browser [e.g. The Arc of the Chrome kernel]

**Smartphone (please complete the following information):**
**Additional context**

**Comment by asieduernest12** [comment]
If you are able to, please inspect the html elements for the inputs for both telegram and discord and paste the code blocks in here as a comment,

**Comment by asieduernest12** [comment]
@ethan-ih if this issue is still persisting for you then make sure to disable JiffyReader(JR) while inputing data
