### ISSUE TITLE
[Error] Unable to parse manifest.json

### ISSUE THREAD

**Issue by FurkanHanciSecond** [ansh/jiffyreader.com#199]
I'm gettin this error when run xcrun safari-web-extension-converter /Users/Desktop/ jiffyreader.com
also i didn't find any "manifest.json" file in the project.

**Comment by ansh** [comment]
@FurkanHanciSecond The app has been released for Safari. Please use the TestFlight link https://testflight.apple.com/join/eFFlcXzz

Let me know if it works.

**Comment by FurkanHanciSecond** [comment]
@ansh yeah it works, but i wanna run the project on xcode how can i do that?

**Comment by ansh** [comment]
You have to build the project first

**Comment by FurkanHanciSecond** [comment]
Okay, thanks ✌️
