### ISSUE TITLE
[FEATURE] I can help with [TRANSLATION] into [GERMAN] language

### ISSUE THREAD

**Issue by geschenkwald** [ansh/jiffyreader.com#201]
**Is your feature request related to a problem? Please describe.**
The current German translation is quite poor and confusing to understand.

**Describe the solution you'd like**
I offer you to do the translation into German.

**Describe alternatives you've considered**
If someone has already agreed to translate the text into German, please let me know as soon as possible.

**Comment by asieduernest12** [comment]
@geschenkwald thank you for this work, I had no idea how bad the automatic translationn is and this is great. 
Will update and deploy this in a few days when we get a chance.
