### ISSUE TITLE
Question: Does jiffy reader work on all webpages?

### ISSUE THREAD

**Issue by in-dabreeze** [ansh/jiffyreader.com#204]
Hi

Jiffy reader does not seem to work on some web pages despite me trying to on the function using the shortcut method.
Can I check if there are web pages that the extension cannot work on? If there is, can I know what type of web pages are those?

x
Amalina

**Comment by asieduernest12** [comment]
Hello Amalina, yes some few websites are disabled due to compatibility and browser crashes and its not worth crashing the browsers of our users.

Notion is one such page.
Let me know what website specifically is bugging out for you and i will investigate later.

**Comment by asieduernest12** [comment]
#166
