### ISSUE TITLE
Ignore links

### ISSUE THREAD

**Issue by pluto-dev** [ansh/jiffyreader.com#209]
Just as the title says, let us disable the "bolding" for links.

**Comment by asieduernest12** [comment]
@pluto-dev awesome suggestion, someone might want it and someone might not.
This feature sure will come in the next version where you can personally add items to be excluded

**Comment by fecet** [comment]
Looking forward to it, I guess it's also possible to ignore math if this feature be implemented?

**Comment by asieduernest12** [comment]
fixed in #316
