### ISSUE TITLE
pdf size become too large

### ISSUE THREAD

**Issue by guaguastandup** [ansh/jiffyreader.com#213]
I'm printing a html of size 4MB to pdf, the size of pdf becomes very large, more than 100MB, is there any optimization method?

**Comment by asieduernest12** [comment]
@guaguastandup not certain we understand your challenge and it is also not in our scope, I dont have any particular idea how to optimize the pdf generation, maybe play with dpi setting by reducing its value which might give you a smaller size but that also makes the pdf less sharp.
