### ISSUE TITLE
[FEATURE] Permanently Disable on Specific Sites

### ISSUE THREAD

**Issue by isprenkle** [ansh/jiffyreader.com#216]
I'm somewhat surprised that the On/Off function doesn't save which sites have been toggled. I would prefer sites be toggled On/Off based on what setting was previously set, something akin to how uBlock Origin and AdBlock Plus act when they're toggled.

**Comment by asieduernest12** [comment]
@isprenkle  use the `turn on/off always` at the bottom to get this behaviour and you can read more on it [here](https://github.com/ansh/jiffyreader.com#always-onoff-button)
