### ISSUE TITLE
[FEATURE] Ability to view/edit the list of excluding sites, with wildcard support

### ISSUE THREAD

**Issue by snoblenet** [ansh/jiffyreader.com#217]
**Is your feature request related to a problem? Please describe.**

When I click the "This Site" button, it's not clear what pages/sites/domains I'm targetting.

Afterwords, it's not clear which pages/sites/domains have been targetted.

**Describe the solution you'd like**

A windows that lists all affected pages/sites/domains in a text area, for viewing and editing.

The list should be one line per rule, with support for wildcards.

For example:

```
https://somesite.com/a-specific-page
https://othersite.com/area/**
https://***.thirdsite.com
```

**Additional context**

This is a common pattern on browser extensions that let you exclude particular pages/sites/domains.

**Comment by asieduernest12** [comment]
@snoblenet please look over docs for the site button provided [here](https://github.com/ansh/jiffyreader.com#site-preferences-button)

**Comment by asieduernest12** [comment]
feel free to open a new issue if this does not address your concern and we will get back to you
