### ISSUE TITLE
Copy/paste doesn't work

### ISSUE THREAD

**Issue by whdmike** [ansh/jiffyreader.com#221]
When plugin is enabled - on this site - somehow copy paste doesn't work. When I disable it, works again. PS. I tried to copy YT url to FB messenger and it didn't work.

**Comment by asieduernest12** [comment]
@whdmike with JiffyReader on, you you have to select the entire word before using using copy to actually copy it.

please try selecting the entire word and clicking copy again.

reopen this issue if issue is still not resolved.

You should also record the issue using the browser from https://replay.io and share the link to the recording here for further assistance.
