### ISSUE TITLE
[BUG] NO MANIFEST.JSON FOUND. Git Clone for Safari does not work. 

### ISSUE THREAD

**Issue by BeverlyLaurelBLVD** [ansh/jiffyreader.com#223]
jiffyreader is missing a manifest.json file it needs to do the conversion so it will work on Safari.

**Comment by asieduernest12** [comment]
@BeverlyLaurelBLVD you can grab the latest build here which includes a manifest file
https://github.com/ansh/jiffyreader.com/releases/download/1.0.9.1010/jiffyReader-chrome.zip

alternatively you can run a build script to generate a build which will include the manifest file
