### ISSUE TITLE
Download does not work on Opera GX

### ISSUE THREAD

**Issue by jkeegan66** [ansh/jiffyreader.com#224]
Program wont download on Opera GX. Says file not found each time I try to download

**Comment by asieduernest12** [comment]
@jkeegan66 thank you for rasing this issue
we can confjirm downloading the extension from google chrome extension store will work for Opera GX

try downloading/installing JiffyReader from google chrome store by [clicking this link](https://www.jiffyreader.com/api/destinations/chrome)

**Comment by jkeegan66** [comment]
Thanks bro, appreciate it
