### ISSUE TITLE
PORTUGUESE translation

### ISSUE THREAD

**Issue by MrBrandtCox** [ansh/jiffyreader.com#230]
{
    "preferenceLabel": {
      "message": "preferência de uso",
      "description": "rótulo para (botão de preferência global ou de site alterna"
    },
    "tipsPopupTriggerLabel": {
      "message": "dicas",
      "description": "rótulo para (botão de preferência global ou de site alterna"
    },
    "globalPreferenceToggleBtnText": {
      "message": "global",
      "description": "texto principal do botão de alternância de preferência global"
    },
    "globalPreferenceToggleBtnSubText": {
      "message": "padrão",
      "description": "subtexto do botão de preferência global"
    },
    "sitePreferenceToggleBtnText": {
      "message": "site",
      "description": "texto principal do botão de alternância de preferência global"
    },
    "sitePreferenceToggleBtnSubText": {
      "message": "para este site",
      "description": "subtexto do botão de preferência global"
    },
    "onOffToggleBtnTextDisable": {
      "message": "desabilitar",
      "description": "texto para o botão desativar" 
    },
    "onOffToggleBtnTextEnable": {
      "message": "habilitar",
      "description": "texto para o botão ativar"  
    },
    "onOffToggleBtnSubText": {
      "message": "modo de leitura",
      "description": "texto para o botão liga/desliga" 
    },
    "defaultShortcutLabelText": {
      "message": "atalho padrão",
      "description": "texto para o atalho padrão"
    },
    "defaultShortcutValueTextChrome": {
      "message": "alt+b",
      "description": "atalho padrão para chrome"
    },
    "defaultShortcutValueTextFirefox": {
      "message": "alt+w",
      "description": "atalho padrão para firefox"
    },
    "saccadesIntervalLabel": {
      "message": "intervalo de sacadas",
      "description": "rótulo para controle deslizante de intervalo de sacadas"
    },
    "fixationsStrengthLabel": {
      "message": "força de fixações",
      "description": "rótulo para controle deslizante de força de fixação"
    },
    "fixationsEdgeOpacityLabel": {
      "message": "opacidade de borda de fixações",
      "description": "rótulo para controle deslizante de opacidade de borda de fixações"
    },
    "saccadesColorLabel": {
      "message": "cor sacada",
      "description": "rótulo para a lista suspensa de cores sacadas"
    },
    "saccadesStyleLabel": {
      "message": "sacadas ",
      "description": "rótulo para menu suspenso de estilo sacada"
    },
    "lineHeightTogglesLabel": {
      "message": "sacadas ",
      "description": "rótulo para botões de altura de linha menores e maiores"
    },
    "smallerLineHieghtBtnText": {
      "message": "aa-",
      "description": "texto para o botão"
    },
    "smallerLineHieghtBtnSubText": {
      "message": "menor",
      "description": "subtexto para o botão"
    },
    "largerLineHieghtBtnText": {
      "message": "aa+",
      "description": "texto para o botão"
    },
    "largerLineHieghtBtnSubText": {
      "message": "maior",
      "description": "subtexto para o botão"
    },
    "defaultBionicModeToggleBtnOffText": {
      "message": "desligue sempre",
      "description": "texto para o botão"
    },
    "defaultBionicModeToggleBtnOnText": {
      "message": "ligar sempre",
      "description": "texto para o botão"
    },
    "defaultBionicModeToggleBtnSubText": {
      "message": "preferência de alternância padrão",
      "description": "subtexto para o botão"
    },
    "resetBtnText": {
      "message": "Redefinir as configurações",
      "description": "texto para o botão"
    },
    "faqLinkText": {
      "message": "Perguntas frequentes",
      "description": "texto do link"
    },
    "reportIssueLinkText": {
      "message": "relatar problema",
      "description": "texto do link"
    },
    "aboutUsLinkText": {
      "message": "O site", 
      "description": "texto do link"
    },
    "dataEntryMessage": {
      "message": "Desligue se o leitor de Jiffy interferir na entrada de dados",
      "description": "texto"
    },
    "googlePlayLinkSecondaryText": {
      "message": "leitura suportada",
      "description": "texto"
    },
    "urlPromptText": {
      "message": "Guias sem url podem não funcionar corretamente",
      "description": "texto"
    },
    "reloadPromptText": {
      "message": "Recarregue a guia com url válido e tente novamente",
      "description": "texto"
    }
  }

**Comment by MrBrandtCox** [comment]
name for attribution @MrBrandtCox.
(I just noticed) If you prefer, I can translate the descriptions back to English. Glad I could help.

**Comment by asieduernest12** [comment]
@MrBrandtCox thank you for this, please resubmit this as a pulll request so that your github profile gets added automatically when we create a release. Is that possible?

**Comment by MrBrandtCox** [comment]
I can do that no problem

**Comment by MrBrandtCox** [comment]
@asieduernest12 I just now found the already made file in your repo for portuguese from another user haha, so case closed and we can close this issue. hanks anyway!!
