### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by thasimo-scholars** [ansh/jiffyreader.com#236]
I think I have found some bug, that broke my whole website. I have been editing a website in nicepage web editor. I just recently downloaded this extention. I think it broke my whole website. It made my whole html crazy, as it split each word separatedly.

here an image from html code
![image](https://user-images.githubusercontent.com/99335441/236243249-9dd2a5d0-906d-48f4-b983-93a5d01b0c5d.png)

Just want to warn everyone, delete it, if you are using some html editor online. As it will directly edit the whole html code. I have no idea how it happened. But if I try to recreate, make a new website and turn this on, it will do the same. Just brick my whole website without being able to revert it. Maybe there is a way? does anyone know? I would be glad. I don't want to redo my work from older backup. please....

**Comment by thasimo-scholars** [comment]
Do you maybe have a script, that could work as the backward of jiffy reader and remove all editing the extension did?

**Comment by asieduernest12** [comment]
I guess you did not see this
![image](https://user-images.githubusercontent.com/20851930/236245073-2abc49e0-1f0b-40f4-8910-336b9f075d57.png)

**Comment by asieduernest12** [comment]
no not at 

> Do you maybe have a script, that could work as the backward of jiffy reader and remove all editing the extension did?

No we do not, but one easy solution is to copy all your code to vs code edit and using the find and replace to remove all the added scripts, it should take you about 5 mins.

Terribly sorry

**Comment by asieduernest12** [comment]
try following in this order 
replace all 
fixation-strength="1" with nothing
do the above with the numbers 1,2,3 and 4
<br-fixation> with nothing
</br-fixation> with nothing
<br-bold> with nothing
</br-bold> with nothing
<br-edge> with nothing
</br-edge> with nothing
<br-span> with nothing
</br-span> with nothing

that should return your site back to normal

**Comment by thasimo-scholars** [comment]
THAT WORKED! THANKS YOU SAVED ME!

**Comment by asieduernest12** [comment]
> THAT WORKED! THANKS YOU SAVED ME!

the least i could do 
![ClipWindowsGIF](https://user-images.githubusercontent.com/20851930/236257229-79de8b32-4764-4b32-857b-b08549c3a2cc.gif)
