### ISSUE TITLE
[FEATURE] changing remaps.

### ISSUE THREAD

**Issue by tokisuno** [ansh/jiffyreader.com#238]
I use i3 and alt is my mod key. Alt+w is impossible for me as that's my bind to open a new firefox window. Alt+B changing my tiling style. Having the ability to rebind would make this program usable for me.

**Comment by asieduernest12** [comment]
@tokisuno you can follow the guide here to set a different key binding

https://github.com/ansh/jiffyreader.com#shortcut

**Comment by tokisuno** [comment]
ty ty
