### ISSUE TITLE
Option to use Dyslexie Font

### ISSUE THREAD

**Issue by JpEncausse** [ansh/jiffyreader.com#24]
You should replace Font Face with Dyslexie Font
https://www.dyslexiefont.com/

**Comment by ansh** [comment]
Unfortunately that font  isn’t free

**Comment by mohitmujawdiya** [comment]
Although I don't need it, Opendyslexic font is free. https://opendyslexic.org/

**Comment by asieduernest12** [comment]
@JpEncausse if this is a request, update the tag and open it again. Hopefully someone works on it for you
