### ISSUE TITLE
[Markdown Support] Bionize markdown files

### ISSUE THREAD

**Issue by techieaditya** [ansh/jiffyreader.com#240]
Would be productive bionizing markdown files and would be of immense help to neurodivergent readers and creaters.
Kind Regards

**Comment by asieduernest12** [comment]
> Would be productive bionizing markdown files and would be of immense help to neurodivergent readers and creaters. Kind Regards

kindly explain what you have in mind @techieaditya. this extensison works on websites. No files involved

**Comment by couldbewoese** [comment]
Depending on what you use to read your markdown files, there are some options that you might find helpful.

Obsidian plug-in: https://github.com/Quorafind/Obsidian-Better-Reading-Mode
Roam Research: https://github.com/fbgallet/Roam-extensions/blob/main/bionic_text.js

**Comment by asieduernest12** [comment]
i supposed this issue is

> Depending on what you use to read your markdown files, there are some options that you might find helpful.
> 
> Obsidian plug-in: https://github.com/Quorafind/Obsidian-Better-Reading-Mode Roam Research: https://github.com/fbgallet/Roam-extensions/blob/main/bionic_text.js

I suppose this issue is resolved then
