### ISSUE TITLE
[BUG] Doesn't apply text style to google docs file

### ISSUE THREAD

**Issue by ETHANTALJAFFE** [ansh/jiffyreader.com#241]
**Describe the bug**
When using the extension on Google Chrome, it doesn't apply the font styling to the contents of the document in Google Docs.
**To Reproduce**
Steps to reproduce the behavior on extension or a specific website:

**Reproduce on a website**
1. Go to docs.google.com
2. Open on any file
3. Notice that the extension doesn't affect the contents of the document

- [ ] check or mark with an x to indicate that the link is publicly accessible and also requires no account to be created.

**Expected behavior**

**Screenshots**
Notice in the screenshot below how it does work on the toolbar but not on the document's content
<img width="1448" alt="image" src="https://github.com/ansh/jiffyreader.com/assets/6400075/c9799e0e-c3c8-40e4-bbef-7462c1f08133">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 113.0.5672.92
 - Extension version [e.g. 1.0.9.1001] 1.0.10.1

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] null
 - OS: [e.g. iOS8.1] null
 - Browser [e.g. stock browser, safari] null
 - Version [e.g. 22] null
 - Extension version [e.g. 1.0.9.1001] null

**Additional context**

**Comment by asieduernest12** [comment]
check through the faq for more tips
