### ISSUE TITLE
[BUG] On some sites, text disappears instead of being dimmed.

### ISSUE THREAD

**Issue by Cerxi** [ansh/jiffyreader.com#242]
**Describe the bug**
When using the extension on certain sites, one example being https://www.tofugu.com/japanese/japanese-pronunciation/?utm_source=Tofugu&utm_medium=Article&utm_campaign=Learn%20Japanese sidebar text disappears entirely instead of being dimmed. Only the bolded parts remain visible, the rest turns completely background white instead of dimming.

**To Reproduce**

1. Go to [an affected website website](https://www.tofugu.com/japanese/japanese-pronunciation/?utm_source=Tofugu&utm_medium=Article&utm_campaign=Learn%20Japanese)
2. Click on 'turn on the extension'
3. The non-bold parts of the sidebar text become white; invisible against the background.

**Expected behavior**
The text to dim, but remain visible

**Screenshots**
![image](https://github.com/ansh/jiffyreader.com/assets/1817514/8bf12832-2eca-4443-a790-36a101a2e199)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser/Version: Vivaldi 6.0.2979.18 (Stable channel), also duplicated on Chrome 113.0.5672.127 (Official Build) (64-bit) to confirm it wasn't a Vivaldi error
 - Extension version: Chrome store 1.0.10.1, tested with beta both on and off

**Additional context**
Bug can be worked around by setting Unfocused Opacity to 100%, or by just selecting the missing text, but this makes reading less efficient, and proper behavior would be preferred.

**Comment by asieduernest12** [comment]
set your opacity to 100% to solve the issue
this is an issue with some css attributes

see #145 
#183

**Comment by asieduernest12** [comment]
> set your opacity to 100% to solve the issue this is an issue with some css attributes
> 
> see #145 #183

![image](https://github.com/ansh/jiffyreader.com/assets/20851930/8798dbda-a4af-4a49-8294-e7638c702b91)
