### ISSUE TITLE
Extension doesn't work for HTML file

### ISSUE THREAD

**Issue by Sandelbossu** [ansh/jiffyreader.com#246]
I followed the instructions regarding the case of a pdf file. I converted it to html, opened it in chrome and the extension doesn't work.
Does it have a dimension limit, or should I just try to convert it to EPUB?

**Comment by asieduernest12** [comment]
@Sandelbossu if you are on chrome, you have to enable JiffyReader to access file urls.
To Enable JiffyReader to access file urls follow the steps below
1. click on the puzzle icon, then click Manage extensions
2. click the details button for JiffyReader
3. find the option to allow access to file url's and turn it on

then load your converted html again and turn on JiffyReader.

Open this ticket again if the steps above do not resolve your issue and provide information on what browser you are using.

**Comment by Sandelbossu** [comment]
I am using chrome, I allowed access to file url's, considering the extension wouldn't even open without the permission. The pdf is 38 MB, so I can't upload it here and the html is not supported, but, maybe, if you wish we can find a way to send it to you so you can see if it works in your case

**Comment by asieduernest12** [comment]
@Sandelbossu upload the pdf and the html to a google drive or your preferred cloud storage of your choice
the link to jiffyreader007@gmail.com or you can paste the link here.

Please do not share the files if they contain any personal identifiable information

**Comment by Sandelbossu** [comment]
This is the link for both the pdf and the html. For context, it has no personal information, it's just a book I'd like to read.
https://drive.google.com/drive/folders/1Wk0Tps3_YgbRfuTi3F3vB_IDMCppxRrT?usp=drive_link

**Comment by asieduernest12** [comment]
@Sandelbossu I see the issue, unfortunately your pdf is a scan and does not include actuall text.
the pdf method only works most time if the pdf source contains actual text.

Sorry.

**Comment by Sandelbossu** [comment]
Right! Makes perfect sense. Thank you for your time and help!

**Comment by asieduernest12** [comment]
Happy to help
