### ISSUE TITLE
[BUG] Site preferences are not saved

### ISSUE THREAD

**Issue by suzdalnitski** [ansh/jiffyreader.com#247]
**Describe the bug**
I've enabled Jiffy Reader globally, but wanted it to be disabled for some websites (eg github). Disabling the extension works fine, but when I reload the page, it is once again enabled.

**To Reproduce**
Steps to reproduce the behavior on extension or a specific website:

**Reproduce on the extension**
1. Go to 'https://github.com/ansh/jiffyreader.com'
2. In the extension, click 'Turn on always'
3. Click on 'Site'
4. Click on 'Disable'
5. Check that Jiffy Reader is disabled on the page
6. Reload the page
7. Jiffy Reader is enabled, while it should have still been disabled.

**Expected behavior**
After reloading the page, Jiffy Reader is still disabled

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura
 - Browser: Chrome
 - Version:  114.0.5735.90
 - Extension version: 1.0.10.1

**Comment by asieduernest12** [comment]
@suzdalnitski thank for bringing this up. A new update will be released to address this issue. Expect the updates to be available tomorrow end or at the middle of next week as each browser store (chrome/firefox) take time to review and approve updates

**Comment by asieduernest12** [comment]
@suzdalnitski our latest version 1.0.10.2 is now available for chrome/chromium based browsers and firefox.
this addresses the issues above.

Restart your browser and it should update automatically or head over to your extensions page to manually force an update.

**Comment by suzdalnitski** [comment]
@asieduernest12 thanks for taking a look! Unfortunately I'm still having the issue. Is there something I'm missing?

Also I'm a little confused by the "Global" and "Turn On/Off always" settings. I have set "turn on always", but disabled for site. Upon page reload it's still enabled for site...

![image](https://github.com/ansh/jiffyreader.com/assets/8169977/470bedf7-447b-4df7-a495-330a1acd40cc)

**Comment by suzdalnitski** [comment]
Thanks for taking the time to record the video! Seems to be working in beta mode (not in classic mode though).

Thank you!
