### ISSUE TITLE
[BUG] facebook edtiable content glitching

### ISSUE THREAD

**Issue by Hikarea** [ansh/jiffyreader.com#250]
**Describe the bug**
I can't write comments on Facebook website, using Edge browser

**To Reproduce**
Steps to reproduce the behavior on extension or a specific website:
Just try to comment on a post on Facebook.com

**Reproduce on the extension**

**Reproduce on a website**
1. Visit this link: '...' 
- [x] check or mark with an x to indicate that the link is publicly accessible and also requires no account to be created.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Extension version [e.g. 1.0.9.1001]

**Smartphone (please complete the following information):**
 - Extension version [e.g. 1.0.9.1001]

**Additional context**

**Comment by asieduernest12** [comment]
@Hikarea thank for reporting this issue. 
I will implement a fix for this that should be available in the next few days.

Casue: comments on facebook are implemented using non standard html resources
Fix: add an exception for the comment element using [role=textarea] and [contenteditable=true]
![image](https://github.com/ansh/jiffyreader.com/assets/20851930/f5b05b00-d94d-4c6e-9508-2f174efbac00)
AltFix: use an ml model to scan the dom and flag editable elements to be excluded from jiffyreader parsing
Issues: user privacy obviously, the model would have to be local if implemented

**Comment by generrosity** [comment]
Hi @asieduernest12 ! just wondering if this was in place?

I see in your screenshot "role=textbox" but in your notes "role=textarea"

Im looking at Yammer/MS Viva Engage which uses the same css classes and would benefit from this :)

**Comment by asieduernest12** [comment]
> Hi @asieduernest12 ! just wondering if this was in place?
> 
> I see in your screenshot "role=textbox" but in your notes "role=textarea"
> 
> Im looking at Yammer/MS Viva Engage which uses the same css classes and would benefit from this :)

Hi @generrosity this is now resolved in the latest build 1.0.10.300 which should be available in the next few days in all extension stores (chrome, opera, firefox).

Unfortunately i am not familiar with Yammer/Ms what is  though?

**Comment by asieduernest12** [comment]
> Yammer/Ms

@generrosity found out what yammer is, so the new update should also work for yammer and any website that has regular input fields and also custom input fields aslong as their are anotated with the contenteditable attribute

**Comment by generrosity** [comment]
> 

Many thanks! It took a while for it to flow through to Chrome, but its working great 👍👍👌

**Comment by asieduernest12** [comment]
awesome feel free to give the project a ratting on chrome store. Helps the prject immensely.
