### ISSUE TITLE
Add-on popup has scroll bars

### ISSUE THREAD

**Issue by noughtnaut** [ansh/jiffyreader.com#253]
**Is your feature request related to a problem? Please describe.**
The add-on popup that opens by clicking on the "rabbit" shows scroll bars. I have my page zoom set to 100%, so that's not why. Zooming the popup affects the entire popup correctly, and so does not affect the scroll bars' existence.

**Describe the solution you'd like**
The popup needs to be ever so slightly bigger?

**Describe alternatives you've considered**
Perhaps it's related to OS UI zoom adjustment? I'm on Windows 10, using the recommended 125% scaling ... but setting it to 100% doesn't fix it.
![image](https://github.com/ansh/jiffyreader.com/assets/73470174/ea4bff75-f5d5-4e6e-b55b-4364b58a842c)

![image](https://github.com/ansh/jiffyreader.com/assets/73470174/1c2cbbd2-78a1-4524-a1a5-890d4d0fca78)

**Comment by asieduernest12** [comment]
@noughtnaut thank you for bringing this issue up.
I looked into the matter and cannot reproduce on my end which makes it challenging to fix an issue that cannot be reproduced.
I will keep an eye for this but I may have to make is not going to be fixed.

You may optionally want to lower the resulotion within windows. The value indicated as recommended is an estimation from windows on what resulotion would be ideal to see artificats on your screen with minimal eye strain and confort if i were to make a guess.

You can adjust the resolution any how you prefere as long as you are able to see easily without straining your eyes.
you may want to reduce the value of the scale which may or may not resolve the issue

**Comment by noughtnaut** [comment]
Not reopening - just saying thank you for a near-immediate response from you. Awesome.
