### ISSUE TITLE
[BUG] Add-on popup displays incorrect shortcut

### ISSUE THREAD

**Issue by noughtnaut** [ansh/jiffyreader.com#254]
**Describe the bug**
This button still lists "Alt-W" after having changed the shortcut to "Ctrl-Alt-J". (Both the button and the modified shortcut work fine though.) I concede that the button says "_default_ shortcut", though...
![image](https://github.com/ansh/jiffyreader.com/assets/73470174/73515ed2-ac23-4334-bbd3-a46cd8ea78a4)

**To Reproduce**
Steps to reproduce the behavior on extension or a specific website:

**Reproduce on the extension**
1. Change the add-on shortcut.
2. Open the popup.
3. Read the button.

**Expected behavior**
It would be sweet if it could list the _actual_ shortcut.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 114.0.2
 - Extension version 1.0.10.2

**Comment by asieduernest12** [comment]
#249

**Comment by asieduernest12** [comment]
#255 fixes this issue for chrome but a later update needs to be made to resovle bug from the feature for firefox, so lets look up to wednesday to have everything resolved with automated updates issues by chrome store and firefox add-ons market
