### ISSUE TITLE
[BUG] Memory leak on Atlassian Jira pages

### ISSUE THREAD

**Issue by krisDunnSoSO** [ansh/jiffyreader.com#257]
I'm using latest chrome and extension version.

Not sure if you have access to a Jira site to replicate but if I load up a Jira issue, the tab will leak memory until it crashes out and chrome will suspend the tab with an out of memory error.
<img width="535" alt="image" src="https://github.com/ansh/jiffyreader.com/assets/127771843/64490bd5-cf1c-440e-8dc6-4b2193fae7c4">

**Comment by asieduernest12** [comment]
@krisDunnSoSO sorry i dont have access to Jira to replicate.
unfortunately it is challenging to fix what i can't see.

maybe you will be able to make a recording with replay.io
hopefully that might be a solution to replicattion if you are able to.

cheers

**Comment by asieduernest12** [comment]
@krisDunnSoSO seems the issue resolved itself.
