### ISSUE TITLE
[FEATURE] Will it work with Google docs

### ISSUE THREAD

**Issue by hackacat707** [ansh/jiffyreader.com#258]
I want to use it to read files on Google docs but it doesn't show up anything. And none of the extensions work

I want it to work with google docs. Currently it only changes the title, not the contents of the document

I mean it works i suppose if i use the bionic reading site. I noticed it works if I use ever note as well.

**Comment by asieduernest12** [comment]
@hackacat707 presently JiffyReader extension cannot work with Google docs.
Google docs will require a dedicated code implementation and effort outside the core scope of the extension 
fingers crossed, something might pop out given enought long nights and incentives to make this a reality.

**Comment by asieduernest12** [comment]
@hackacat707 you can follow the guide for working with google docs here https://github.com/ansh/jiffyreader.com/issues/258

**Comment by hackacat707** [comment]
@asieduernest12  where?

**Comment by asieduernest12** [comment]
@hackacat707 https://github.com/ansh/jiffyreader.com#google-docs-support-publish-method
sorry i forgot to add the link.
