### ISSUE TITLE
Doesnt work on notion site

### ISSUE THREAD

**Issue by ill523** [ansh/jiffyreader.com#263]
**Describe the bug**
The extension doesn't work on the notion site at 

**To Reproduce**
Steps to reproduce the behavior on extension or a specific website: Go to notion

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]
 - Extension version [Latest Update]

![Screenshot (10)](https://github.com/ansh/jiffyreader.com/assets/94802926/2a71b10e-25f6-4070-b3b2-f20b94510cc5)

**Comment by asieduernest12** [comment]
support for notion is disabled due to unstable performance
see #166
