### ISSUE TITLE
[FEATURE] Local processing vs server callback

### ISSUE THREAD

**Issue by generrosity** [ansh/jiffyreader.com#265]
**Is your feature request related to a problem? Please describe.**
The other jiffy-like browser plugin uses server callback apis to process all the website data.

Your website doesn't mention the actual method you use to process the text "how it works" - and your 'terms and conditions' page (iubenda) on the website looks to be broken.

**Describe the solution you'd like**
Confirmation if website data gets uploaded to server api's to be processed. I work with some government departments, and their accessibility working groups would love to use this for our ADHD users.

If you are using server API, I would still love to see a Feature for 'local processing only'. I understand that local processing might have quite a limited ability to function and use some of the newer AI juices (to the point of 'one third of word'), but I think it would be wonderful as an option.

**Describe alternatives you've considered**
Its been really hard to find things due to the wording of what I'm looking for.

Thanks for your consideration! I hope the Beta is going well 💚

**Comment by asieduernest12** [comment]
thank you  @generrosity for your consideration.

JiffyReader is local, performs all data transformation and rendering locally without sending the markup a given website to any remote api or backend service.

Note that JiffyReader can break forms and form inputs and we do not advice you to use JiffyReader where or when  you will be entering and making updates to information on or within a website.
