### ISSUE TITLE
Possibly improved split algorithm

### ISSUE THREAD

**Issue by lquenti** [ansh/jiffyreader.com#28]
In other languages like german, words can get stupidly long. For this, even a half split maybe is too long.

I thought about implementing it myself, and I think something like `ceil(log2(word.length))` would scale better.

Probably something to A-B test, just an idea.

Nonetheless, thanks for your contribution!

**Comment by lquenti** [comment]
or any other log base, depending on how you want it to scale with word length.

for reference: the logarithm base change theorem https://proofwiki.org/wiki/Change_of_Base_of_Logarithm

**Comment by asieduernest12** [comment]
Sounds like a good to AB test

**Comment by peti123x** [comment]
Hi, created a PR for this: https://github.com/ansh/bionic-reading/pull/42
I agree ceil(log2(n)) works okay for now (at least in english), and as the PR suggests there are different approaches we could take following this to make the algorithm better and more performant based on context.

**Comment by lquenti** [comment]
Thank you so much!

**Comment by asieduernest12** [comment]
@lquenti presently with the latest release, it is possible personalize the fixation strength on a word by using a slider.
But it seems to be an interesting problem and leaving it to the final user to choose how much or how little fixation the prefer is ideal.
