### ISSUE TITLE
[BUG] Automatic 1111 Stable Diffusion Webui page freeze/slow

### ISSUE THREAD

**Issue by thijsi123** [ansh/jiffyreader.com#281]
**Describe the bug**
The webui page does or does not load, loads slowly freezes, and page navigation is also slow

**To Reproduce**
Steps to reproduce the behavior on extension or a specific website:

**Reproduce on the extension**
1. Start Automatic 1111 Stable Diffusion Webui
2. Go to http://127.0.0.1:7860/
3. result
**Reproduce on a website**
1. Visit this link: 'http://127.0.0.1:7860/' 
- [ ] check or mark with an x to indicate that the link is publicly accessible and also requires no account to be created.

**Expected behavior**
It should load the page as fast as usual not cause it to freeze, it should also not slow down navigating the the page.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version 117.0.2045.47 (Official build) (64-bit)
 - Extension version: 1.1.2

**Comment by asieduernest12** [comment]
@thijsi123 I want to invesigate this issue but the links in step 2 and 4 will work only on your computer. So this issue cannot be investigated as is

**Comment by asieduernest12** [comment]
for the issue you are experiencing, it is possible that you have a huge amount of html nodes on your site or some js codes are triggering jiffyreader observer

**Comment by thijsi123** [comment]
I'd like to help, but I don't know how, also, I can't use my PC for the weekend.

**Comment by asieduernest12** [comment]
@thijsi123 it is outright impossible to investigate this problem since the webpage is local and only available on your computer.
Alternatively, we can schedule a zoom this weekend and i could take a look and see what might be causing the issue.
