### ISSUE TITLE
[BUG] Youtube videos on twitter won't play when Jiffy Reader chrome extension is active

### ISSUE THREAD

**Issue by altFAB74** [ansh/jiffyreader.com#282]
**Describe the bug**
Youtube videos on twitter won't play when Jiffy Reader chrome extension is active.

Win 11 pro 22H2 x64 / Chrome 118.0.5993.71 (x64) / extension version 1.1.2

**Comment by asieduernest12** [comment]
@altFAB74 provide the link to tweet with manifests this issue so it can be investigated

**Comment by altFAB74** [comment]
Any tweet with an embedded youtube video.
like
https://twitter.com/rickt02865896/status/1712017166558474708

**Comment by asieduernest12** [comment]
reponed with 1.1.4 since 1.1.3 is breaking other websites #286
