### ISSUE TITLE
[BUG] JiffyReader breaking layouts

### ISSUE THREAD

**Issue by xdhmoore** [ansh/jiffyreader.com#286]
**Describe the bug**
Since the most recent update, JiffyReader is breaking the layout of some webpages such as:
* crunchyroll
* pocket reader

**To Reproduce**
Steps to reproduce the behavior on extension or a specific website:

**Reproduce on the extension**
I realize these sites require free accounts, but these are the only examples i have.

1. Manually turn off all extensions
2. Create free accounts on getpocket.com and crunchyroll.com
3. Load the following two sites:
https://www.crunchyroll.com/watch/GWDU8QVDJ/a-countercharge-law-and-kids-return-attack-combination
https://getpocket.com/read/3951582871
4. They should load normally
5. Enable the JiffyReader extension
6. Click the JiffyReader button and set it to use Global for the two sites and make sure that its set to always off
6. Ctrl+Shift+R to force reload on both of the sites

**Expected behavior**
Pages should load normally. Note that JiffyReader is enabled, but turned off.

**Actual behavior**
Page layout is broken to the point where the page is unusable.

**Screenshots - Attached**
* crunchyroll - Note the extra scrollbar on the right of the crunchyroll page, the presence of two different view areas (I think 1 is the pause picture) and the lack of media control buttons.
* getpocket - the pocket article page is completely unusable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 119.0b9
 - Extension version: 1.1.3

![image](https://github.com/ansh/jiffyreader.com/assets/5142129/faf9878d-202e-49b6-9e39-3bdbc5341462)
![image](https://github.com/ansh/jiffyreader.com/assets/5142129/d7fa2930-e75c-4761-b5c7-05e472f182d8)

**Comment by JarinArenos** [comment]
Confirmed that this is affecting multiple websites

**Comment by asieduernest12** [comment]
update to 1.1.4 or above for issue resolution

**Comment by JarinArenos** [comment]
Thanks!
