### ISSUE TITLE
[BUG] Text disappears when using the extension on Reddit

### ISSUE THREAD

**Issue by Nadni** [ansh/jiffyreader.com#288]
**Describe the bug**
When activating the JiffyReader browser extension on Reddit, the text disappears rather than changing. This happens to me on both Chrome and Firefox.

**To Reproduce**
- Access any page in the website https://www.reddit.com/ in either Chrome or Firefox;
- Activate the extension.

**Expected behavior**
The text in the page is replaced with its "bionic" version.

**Screenshots**
1) Web page when the extension is active:
![with](https://github.com/ansh/jiffyreader.com/assets/27709839/64a45b87-70f8-4b9b-847b-0d98123a3bd2)
2) Web page without the extension:
![without](https://github.com/ansh/jiffyreader.com/assets/27709839/b2f170f9-9dec-41a6-9f3f-3b3fa037e2dd)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: either Chrome (118.0.5993.118) or Firefox (119.0)
 - Extension version: 1.1.4

**Comment by asieduernest12** [comment]
@Nadni  It appears reddit may have implemented some visual updates which is resulting in the present issue.
Hopefully someone takes a stab at fixing it and we merge the fix pr.

**Comment by ChuanyuXue** [comment]
Same

**Comment by jiffyreader007** [comment]
same as #291
