### ISSUE TITLE
[FEATURE] Auto-Enable on Certain Sites

### ISSUE THREAD

**Issue by Anas-Dew** [ansh/jiffyreader.com#294]
**Is your feature request related to a problem? Please describe.**
It's a hassle turning on and off many times. Because sometimes I want it and sometimes I do not want it.

**Describe the solution you'd like**
We can have a option to add our fav sites into it and it will automatically turn on jiffy reader whenever I visit those sites

**Describe alternatives you've considered**
null

**Additional context**
null

**Comment by asieduernest12** [comment]
Here this is what you are looking for
https://studio.youtube.com/video/Qn4y_QUqEjE/edit

**Comment by Anas-Dew** [comment]
Thanks buddy
