### ISSUE TITLE
[BUG] Been testing the network speed

### ISSUE THREAD

**Issue by mirrorHe** [ansh/jiffyreader.com#301]
I found that this plugin requested 100 gigabytes of traffic today。
![Uploading PixPin_2024-08-23_17-57-02.png…]()

**Comment by mirrorHe** [comment]
![PixPin_2024-08-23_17-57-02](https://github.com/user-attachments/assets/0b438eb9-463f-4c69-aed1-dbdd5ddd4eb8)

**Comment by ansh** [comment]
This is a bug introduced in 1.1.7

Please upgrade to 1.1.9 @mirrorHe
