### ISSUE TITLE
memorize website preferences

### ISSUE THREAD

**Issue by simultsop** [ansh/jiffyreader.com#51]
It would be nice if it memorizes the line height (smaller, bigger) based on site and the toggle be consistent.. Toggle by default sometimes does not take effect.

Excellent project!

**Comment by TheKruspe** [comment]
A whitelist/blacklist would be handy as well.

**Comment by asieduernest12** [comment]
taken care of by #111 and [release 0.0.5](https://github.com/ansh/jiffyreader.com/releases/tag/0.0.5)
