### ISSUE TITLE
K or m quantities should not be bold

### ISSUE THREAD

**Issue by winkbrace** [ansh/jiffyreader.com#60]
For example on youtube, views are indicated in short text notation. This becomes

118**K**

Do you agree it would look better in all normal font weight?

118K

**Comment by ansh** [comment]
@winkbrace Can you give an example of this issue?

**Comment by winkbrace** [comment]
https://www.youtube.com/ :)

**Comment by asieduernest12** [comment]
> For example on youtube, views are indicated in short text notation. This becomes
> 
> 118**K**
> 
> Do you agree it would look better in all normal font weight?
> 
> 118K

Pretend it is normal font weight😎
![PeaceOutIceAgeGIF](https://user-images.githubusercontent.com/20851930/173542854-527363e3-6d7a-432c-9fe5-50d863313e8d.gif)
