### ISSUE TITLE
Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by FahimFBA** [ansh/jiffyreader.com#68]
We are getting an error saying the manifest version 2 is deprecated. Check the picture below.

<br>

![Screenshot 2022-05-26 002946](https://user-images.githubusercontent.com/64195132/170340523-2dfec55f-6b44-47b3-b5e4-171e2feead43.png)

**Comment by TheCedarPrince** [comment]
Can confirm I am also getting this but it doesn't prevent the extensions from being used at the moment.

**Comment by Cveinnt** [comment]
It looks like migrating to V3 manifest is a bit more complicated then I thought - the webpack-extension-reloader package used for this extension is no longer maintained and does not support V3, more [here](https://github.com/rubenspgcavalcante/webpack-extension-reloader/issues/125), which means the service worker registration will fail for v3 manifests.

**Comment by ansh** [comment]
@Cveinnt We were using v3 before but had to switch to v2 to support Firefox. 

Do you have any suggestions on moving back to v3? @mehbubhussain

**Comment by asieduernest12** [comment]
chrome is the one complaining about version 3 and we can add an extra build step to process the manifest file to work correctly with v3
this also has to account for some of the api calls chrome.tabs.sendMessage and chrome.runtime

**Comment by neelkarma** [comment]
> It looks like migrating to V3 manifest is a bit more complicated then I thought - the webpack-extension-reloader package used for this extension is no longer maintained and does not support V3 (more [here](https://github.com/rubenspgcavalcante/webpack-extension-reloader/issues/125)) which means the service worker registration will fail for v3 manifests.

Looks like a company maintains a fork of it over at https://github.com/SimplifyJobs/webpack-ext-reloader/ and that there is an issue tracking MV3 support there over at https://github.com/SimplifyJobs/webpack-ext-reloader/issues/28

**Comment by asieduernest12** [comment]
We can close this, since we are now using the plasmo framework and the chrome build has manifest v3.
 i am still learning how to use it well but it looks ok for now. though not version 1 actually so potential issues could arrise.

Firefox build will still be on v2 till they switch the browser to demand v3 by default
