### ISSUE TITLE
Feature Request: Is it possible to use this extension for local epub files(opened in chrome using extension) ?

### ISSUE THREAD

**Issue by amatya-aditya** [ansh/jiffyreader.com#76]
Can this be done?  It would be much helpful if it can be used for the local epub files which is opened in chrome using epub extension. Thank you for this awesome extension mate.

**Comment by HaveF** [comment]
Plugin is a bit complex.
Just support [web mode of Calibre](https://github.com/ansh/jiffyreader.com/issues/83) is ok.

**Comment by ansh** [comment]
#83 is actually a better issue than this one.

**Comment by asieduernest12** [comment]
see https://github.com/ansh/jiffyreader.com/issues/83#issuecomment-1197797893

**Comment by asieduernest12** [comment]
> Plugin is a bit complex. Just support [web mode of Calibre](https://github.com/ansh/jiffyreader.com/issues/83) is ok.

Calibre web mode cannot be supported as they are utilizing some enhanced security features preventing the extension from accessing the contents of the epub when it is displayed in the browser.

**Please see the readme section on using epubs with google books which works nice with jiffy reader**
https://github.com/ansh/jiffyreader.com#google-play-books-native-epub-and-pdf-support
