### ISSUE TITLE
Not working for the Epub  ??? 

### ISSUE THREAD

**Issue by amatya-aditya** [ansh/jiffyreader.com#83]
This time I'm using Calibre as the content server for my epub book. But It's still not working. Am I doing something wrong or Is this feature still not available ? 
 
![image](https://user-images.githubusercontent.com/63241408/170731031-3db0e85a-2ac5-49d8-a606-5da58584ba6b.png)
![image](https://user-images.githubusercontent.com/63241408/170731095-390fa1e7-04bd-41c3-8b4f-07dcd57a6570.png)

**Comment by ansh** [comment]
This feature is not available. Closing in favor of #76

**Comment by asieduernest12** [comment]
@amatya-aditya You can view all your epubs if you upload them to Google books.
Presently version 1.0.8.1300 and above should also work for local files but in the case of calibre served content it fails

**Comment by amatya-aditya** [comment]
It's working for the google books. But how do I make it work for the local epub files?
