### ISSUE TITLE
Doesn't work that well on sites where the font is already bold

### ISSUE THREAD

**Issue by kasdeya** [ansh/jiffyreader.com#9]
If the site's font is already **bold** its hard to tell a difference, on other sites I tried where the font is normal, it works really well.

**Comment by ansh** [comment]
@kasdeya Can you give some examples for testing?

**Comment by Alz2709** [comment]
@ansh I have the same issue for emails in Gmail that contain text in bold. This potentially suggests that the issue can be reproduced by such an email.

**Comment by Alz2709** [comment]
@ansh actually I just realised, you can use the "Issues" page of this project to see the problem, because the names are in bold text. https://github.com/ansh/bionic-reading/issues

**Comment by kasdeya** [comment]
> @kasdeya Can you give some examples for testing?

https://thoughtbot.com/blog/io-in-ruby

Try it in this site, I'm using brave browser and it doesn't make much difference in here.

**Comment by Albonycal** [comment]
and it doesn't work at all on twitter
