### ISSUE TITLE
elements added dynamically after first run of br bolding are not bollded

### ISSUE THREAD

**Issue by asieduernest12** [ansh/jiffyreader.com#92]
This can be fixed with an observer on the document that runs the boldening script when new elements are added to the page

register the observer when body.br-bold is present
remove the observer when body.br-bold is removed

**Comment by asieduernest12** [comment]
#8

**Comment by ansh** [comment]
Ah this is the problem with any website with infinite scroll right? So Twitter.com is probably a big issue.

**Comment by asieduernest12** [comment]
yup any website that basically adds new elements using js, so technically also sites built with vue, angular, react
